version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: gclamp
    environment:
      MYSQL_USERNAME: root
      MYSQL_DATABASE: gclamp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3069:3306"  
    volumes:
      - dbdata:/var/lib/mysql
    # (this is just an example, not intended to be a production configuration)

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: gcflash_pma
    restart: always
    ports:
      - 8087:80
    environment:
      PMA_HOST: gclamp
volumes:
  dbdata: