version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_DATABASE: gclamp
      MYSQL_PASSWORD: password
    # (this is just an example, not intended to be a production configuration)

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db  
      PMA_ARBITRARY: 1